plugin:
    name: 'luismayta.web::lang.plugin.name'
    description: 'luismayta.web::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-cubes
    homepage: ''
navigation:
    main-menu-item:
        label: Web
        url: luismayta/web/sitiocontrollers
        icon: icon-cubes
        sideMenu:
            side-menu-item:
                label: 'Configuracion sitio'
                url: luismayta/web/sitiocontrollers
                icon: icon-cogs
            side-menu-item2:
                label: Banners
                url: luismayta/web/bannerscontrollers
                icon: icon-sitemap
