list: $/luismayta/web/models/banners/columns.yaml
modelClass: LuisMayta\Web\Models\Banners
title: BannersControllers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/web/bannerscontrollers/update/:id'
