list: $/luismayta/web/models/sitio/columns.yaml
modelClass: LuisMayta\Web\Models\Sitio
title: SitioControllers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/web/sitiocontrollers/update/:id'
