name: Configuracion
form: $/luismayta/web/models/configuracion/fields.yaml
modelClass: LuisMayta\Web\Models\Configuracion
defaultRedirect: luismayta/web/configuracion
create:
    redirect: 'luismayta/web/configuracion/update/:id'
    redirectClose: luismayta/web/configuracion
update:
    redirect: luismayta/web/configuracion
    redirectClose: luismayta/web/configuracion
